### ISSUE TITLE
libansilove ported to PS3

### ISSUE THREAD

**Issue by bucanero** [ansilove/libansilove#10]
Hello! thanks for your work on libansilove !

not really an issue, but I wanted to let you know that I've forked libansilove and built a wrapper to create ARGB textures (instead of `.png` files) to use them directly on the PlayStation 3.

Based on the generated `ansi` textures, I built an ANSi Viewer for the PS3: https://github.com/bucanero/ansiview-ps3

The app supports browsing and viewing local files, and also browse the complete archive from 16colo.rs 😄 

cheers!

**Comment by bart-d** [comment]
Do you happen to have a recording? I'd like to see it but I don't own a PS3 :)

I see that you've integrated 16colo.rs through plain FTP, note that there is also a public API that allows also to fetch metadata: https://16colo.rs/api.php

**Comment by bucanero** [comment]
hello @bart-d 

I don't have a video, but I'm going to make a quick video and upload it to Youtube 👍 

I had no idea about the API, but I went with FTP because it didn't require any SSL, as using secure connections on PS3 is a bit painful. To run homebrew on PS3, you either need to have custom firmware (or patches), and usually means having some older firmware with outdated certs.
Those old certs can bring issues when trying to get https content with the internal PS3 http functions.
An option would be using libcurl, but I need to update it to a newer version first.

In any case, ftp works for now (although it's slower), and I'm doing some local caching so once you download a file, you don't need it to download it again.

I'll share back the video URL when it's available

**Comment by bucanero** [comment]
Here's a video demo of ANSi View (PS3) https://www.youtube.com/watch?v=OokESQwFKLw

The example shows this file: https://16colo.rs/pack/lgcy-002/fr-dangergirl.ans

(btw, the app includes a mod player, and the background music comes from within the app)

**Comment by fcambus** [comment]
Better late than never, this is now listed in the newly introduced "Projects using libansilove" in the README.

Thanks for sharing this!

**Comment by bucanero** [comment]
> Better late than never, this is now listed in the newly introduced "Projects using libansilove" in the README.
> 
> Thanks for sharing this!

thanks @fcambus ! 🙏  
Lately I've been doing some PS4 homebrew apps, so hopefully at some point I'll port the "ANSi Viewer" to the PlayStation 4 too 😄 

(oh, and I should also update the code to use the 16colo.rs API since I have a full `libcurl` working now)
