### ISSUE TITLE
Inferring font height for XBins with no font data

### ISSUE THREAD

**Issue by andyherbert** [ansilove/libansilove#6]
Quick question regarding your interpretation on parsing XBins with no font data, should not he font height byte be set to 16 or 0?

This is sort of an academic point, because I believe that PD saves font data for all XBins, but I’d thought I’d ask because ansilove fails when it’s 0, but PD loads it successfully because it infers the 8x16 CP437 font.

**Comment by fcambus** [comment]
It seems there is at least one XBin file in the wild with a Fontsize byte set to 0: https://16colo.rs/pack/blocktronics-dsotb/cx-notyet.xb. Not sure what tool was used to create it. It fails to load with every DOS editors and viewers, but indeed loads correctly in PabloDraw.

So yes in this case, I believe we should set the Fonsize byte to 16 in case its value is zero. Want to send a PR?

**Comment by fcambus** [comment]
Fixed in 899618235a29223f29dddaa3e969edb53c4af21c, thanks Andy!
